### PR TITLE
Unable to convert self-referring instances to resources

### LINKED ISSUE #1: Unable to convert self-referring instances to resources
- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

Imagine the following example:
```php
class Parent {
    /** @var Child[] */
    public $childs;
    public function addChild(Child $child) {
        $this->childs[] = $child;
        $child->parent = $this;
    }
}
class Child {
    /** @var Parent */
    public $parent;
}

$parent = new Parent();
$parent->addChild(new Child());
$parent->addChild(new Child());

$generator->fromObject($parent, $request);
// the call above will result in an error:
// Error : Maximum function nesting level of '256' reached, aborting!
```

Other examples:
[One-To-One, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-bidirectional)
[One-To-One, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-self-referencing)
[One-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-bidirectional)
[One-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-self-referencing)
[Many-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-bidirectional)
[Many-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-self-referencing)

The zfcampus/zf-hal component solved this issue by using a `$maxDepth` [property in metadata](https://github.com/zfcampus/zf-hal/blob/master/src/Metadata/Metadata.php#L119) which is then passed through [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L647) and [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L674).

Using this approach would result in a change of the `\Zend\Expressive\Hal\ResourceGenerator\StrategyInterface` interface which would be a BC break.

I would love if someone comes up with an alternate solution which will not break BC.

---

Originally posted by @tobias-trozowski at https://github.com/zendframework/zend-expressive-hal/pull/57

### PR DESCRIPTION
**Pull request by tobias-trozowski**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes (#1)
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description
- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.

```php
$parent = new TestAsset\FooBar;
$parent->id = 1234;
$parent->foo = 'FOO';
$parent->bar = $parent;

$generator->fromObject($parent, $request);
// the call above will result in an error:
// Error : Maximum function nesting level of '256' reached, aborting!
```
Additional examples:
[One-To-One, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-bidirectional)
[One-To-One, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-self-referencing)
[One-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-bidirectional)
[One-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-self-referencing)
[Many-To-Many, Bidirectional](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-bidirectional)
[Many-To-Many, Self-referencing](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-self-referencing)

The zfcampus/zf-hal component solved this issue by using a $maxDepth [property in metadata](https://github.com/zfcampus/zf-hal/blob/master/src/Metadata/Metadata.php#L119) which is then passed through [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L647) and [here](https://github.com/zfcampus/zf-hal/blob/master/src/Plugin/Hal.php#L674).

Using this approach will result in a change of the \Zend\Expressive\Hal\ResourceGenerator\StrategyInterface interface which is a BC break.

This PR is based on my [original PR](https://github.com/zendframework/zend-expressive-hal/pull/57) in zend-expressive-hal.

The following public methods changed (added new argument `int $depth` with default value)
- Metadata\RouteBasedResourceMetadata::__construct
- ResourceGenerator::fromObject
- ResourceGenerator\StrategyInterface::createResource
- ResourceGenerator\RouteBasedCollectionStrategy::createResource
- ResourceGenerator\RouteBasedResourceStrategy::createResource
- ResourceGenerator\UrlBasedCollectionStrategy::createResource
- ResourceGenerator\UrlBasedResourceStrategy::createResource

### CODE REVIEW

File: src/ResourceGenerator.php [hunk 1]
```diff
@@ -124,7 +124,7 @@ public function fromArray(array $data, string $uri = null) : HalResource
      *     against types registered in the metadata map.
      * @param ServerRequestInterface $request
      */
-    public function fromObject($instance, ServerRequestInterface $request) : HalResource
+    public function fromObject($instance, ServerRequestInterface $request, int $depth = 0) : HalResource
```
Comment (weierophinney) [inline src/ResourceGenerator.php:127]: This is a BC break. Classes extending this one and defining using the previous signature will produce a warning under PHP 7, and a fatal under PHP 8, due to signature mismatch. We'll need to target next major for this.

**Review by weierophinney — COMMENTED** [review]
This will need to target 2.0.0. I'm creating a 2.0.x branch now, and will rebase this against it for you momentarily.
